### ISSUE TITLE
Portfolio處如何更改相片與文字，以及點進照片後的頁面更改

### ISSUE THREAD

**Issue by Fater93** [bboyleonp666/agency-jekyll-theme#3]
<img width="1148" alt="截圖 2024-09-15 下午6 48 14" src="https://github.com/user-attachments/assets/bcd63a89-ea21-4974-81bd-be7c4d9b545b">

下方照片為點擊圖片後分頁
<img width="1148" alt="截圖 2024-09-15 下午6 49 41" src="https://github.com/user-attachments/assets/c25818eb-1b1e-40be-9b06-bf6f3c0e12ad">

**Comment by bboyleonp666** [comment]
可以參考 `_portfolio/` 下面的 md 檔
他支援使用 markdown 格式寫內容
